language: android
jdk: oraclejdk8
cache: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
addons:
    sonarqube:
        organization: "zandkorrel-github"
        token:
            secure: f65271edd211baa9bce0aedb96573c4217b82401
        branches:
            - master
            - develop
            
branches:
    only:
        - master
        - develop
            
script:
    - sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=zandkorrel-github -Dsonar.login=f65271edd211baa9bce0aedb96573c4217b82401
        